### ISSUE TITLE
test: run github workflows conditionally

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/insert-name-here#11]
For example, run the `test-sensor-codebase` job only when something in the sensor subdirectory has changed.

We could implement this, by creating a cache after each successful run of the sensor directory tests with the hash of the directory. That way, tests will only run, when the hash changes or the previous test on the same hash failed.

**Comment by empicano** [comment]
For the scope naming, I'd go with what Karma specifies:

> The `<scope>` can be empty (e.g. if the change is a global or difficult to assign to a single component), in which case the parentheses are omitted. In smaller projects such as Karma plugins, the `<scope>` is empty.

**Comment by dostuffthatmatters** [comment]
Who is Karma?

**Comment by dostuffthatmatters** [comment]
Aaaah 🫡

I thought you were contributing to the issue in some way 😉😅

**Comment by empicano** [comment]
Of course not.

If case you _were_ looking for meaningful contributions: We don't need to hack around with hashes. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
